[package]
name = "site-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
iocraft = "0.7"
smol = "2.0"
serde = { version = "1.0", features = ["derive"] }
surf = "2.3.2"
minimad = "0.13.1"
